/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Multicall } from "./Multicall";
export type { XmasTree } from "./XmasTree";
export * as factories from "./factories";
export { Multicall__factory } from "./factories/Multicall__factory";
export { XmasTree__factory } from "./factories/XmasTree__factory";
