/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Multicall } from "./Multicall.js";
export type { XmasTree } from "./XmasTree.js";
// export * as factories from "./factories";
export { Multicall__factory } from "./factories/Multicall__factory.js";
export { XmasTree__factory } from "./factories/XmasTree__factory.js";
