/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace IXmasTree {
  export type TreeStruct = {
    owner: AddressLike;
    ornamentCount: BigNumberish;
    bgId: BigNumberish;
    ornamentIds: BigNumberish[];
    adorners: AddressLike[];
    minted: boolean;
  };

  export type TreeStructOutput = [
    owner: string,
    ornamentCount: bigint,
    bgId: bigint,
    ornamentIds: bigint[],
    adorners: string[],
    minted: boolean
  ] & {
    owner: string;
    ornamentCount: bigint;
    bgId: bigint;
    ornamentIds: bigint[];
    adorners: string[];
    minted: boolean;
  };

  export type BackgroundStruct = { priceUnit: BigNumberish; uri: string };

  export type BackgroundStructOutput = [priceUnit: bigint, uri: string] & {
    priceUnit: bigint;
    uri: string;
  };

  export type OrnamentStruct = {
    owner: AddressLike;
    priceUnit: BigNumberish;
    name: string;
    uri: string;
  };

  export type OrnamentStructOutput = [
    owner: string,
    priceUnit: bigint,
    name: string,
    uri: string
  ] & { owner: string; priceUnit: bigint; name: string; uri: string };
}

export interface XmasTreeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "XMAS"
      | "XmasNFT"
      | "__XmasTree_init"
      | "adorn"
      | "createTree"
      | "getTree"
      | "mint"
      | "nextTreeId"
      | "ownedTrees"
      | "owner"
      | "registerBackground"
      | "registerOrnament"
      | "registerOrnaments"
      | "renounceOwnership"
      | "transferOwnership"
      | "userAdorned"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Adorn"
      | "Initialized"
      | "OwnershipTransferred"
      | "TreeCreated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "XMAS", values?: undefined): string;
  encodeFunctionData(functionFragment: "XmasNFT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "__XmasTree_init",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "adorn",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createTree",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTree",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "mint", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "nextTreeId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ownedTrees",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerBackground",
    values: [IXmasTree.BackgroundStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "registerOrnament",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerOrnaments",
    values: [IXmasTree.OrnamentStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userAdorned",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "XMAS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "XmasNFT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "__XmasTree_init",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "adorn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createTree", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getTree", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nextTreeId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownedTrees", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerBackground",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerOrnament",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerOrnaments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userAdorned",
    data: BytesLike
  ): Result;
}

export namespace AdornEvent {
  export type InputTuple = [
    user: AddressLike,
    treeId: BigNumberish,
    ornamentId: BigNumberish,
    position: BigNumberish,
    ornamentCount: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    treeId: bigint,
    ornamentId: bigint,
    position: bigint,
    ornamentCount: bigint
  ];
  export interface OutputObject {
    user: string;
    treeId: bigint;
    ornamentId: bigint;
    position: bigint;
    ornamentCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreeCreatedEvent {
  export type InputTuple = [owner: AddressLike, treeId: BigNumberish];
  export type OutputTuple = [owner: string, treeId: bigint];
  export interface OutputObject {
    owner: string;
    treeId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface XmasTree extends BaseContract {
  connect(runner?: ContractRunner | null): XmasTree;
  waitForDeployment(): Promise<this>;

  interface: XmasTreeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  XMAS: TypedContractMethod<[], [string], "view">;

  XmasNFT: TypedContractMethod<[], [string], "view">;

  __XmasTree_init: TypedContractMethod<
    [owner_: AddressLike, XMAS_: AddressLike, XmasNFT_: AddressLike],
    [void],
    "nonpayable"
  >;

  adorn: TypedContractMethod<
    [treeId: BigNumberish, ornamentId: BigNumberish],
    [void],
    "payable"
  >;

  createTree: TypedContractMethod<[bgId: BigNumberish], [void], "payable">;

  getTree: TypedContractMethod<
    [treeId: BigNumberish],
    [IXmasTree.TreeStructOutput],
    "view"
  >;

  mint: TypedContractMethod<[treeId: BigNumberish], [void], "nonpayable">;

  nextTreeId: TypedContractMethod<[], [bigint], "view">;

  ownedTrees: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerBackground: TypedContractMethod<
    [bgs: IXmasTree.BackgroundStruct[]],
    [void],
    "nonpayable"
  >;

  registerOrnament: TypedContractMethod<
    [name: string, uri: string],
    [void],
    "payable"
  >;

  registerOrnaments: TypedContractMethod<
    [os: IXmasTree.OrnamentStruct[]],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  userAdorned: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "XMAS"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "XmasNFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "__XmasTree_init"
  ): TypedContractMethod<
    [owner_: AddressLike, XMAS_: AddressLike, XmasNFT_: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "adorn"
  ): TypedContractMethod<
    [treeId: BigNumberish, ornamentId: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "createTree"
  ): TypedContractMethod<[bgId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "getTree"
  ): TypedContractMethod<
    [treeId: BigNumberish],
    [IXmasTree.TreeStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "mint"
  ): TypedContractMethod<[treeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "nextTreeId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ownedTrees"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerBackground"
  ): TypedContractMethod<
    [bgs: IXmasTree.BackgroundStruct[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerOrnament"
  ): TypedContractMethod<[name: string, uri: string], [void], "payable">;
  getFunction(
    nameOrSignature: "registerOrnaments"
  ): TypedContractMethod<
    [os: IXmasTree.OrnamentStruct[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userAdorned"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "Adorn"
  ): TypedContractEvent<
    AdornEvent.InputTuple,
    AdornEvent.OutputTuple,
    AdornEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TreeCreated"
  ): TypedContractEvent<
    TreeCreatedEvent.InputTuple,
    TreeCreatedEvent.OutputTuple,
    TreeCreatedEvent.OutputObject
  >;

  filters: {
    "Adorn(address,uint256,uint256,uint256,uint8)": TypedContractEvent<
      AdornEvent.InputTuple,
      AdornEvent.OutputTuple,
      AdornEvent.OutputObject
    >;
    Adorn: TypedContractEvent<
      AdornEvent.InputTuple,
      AdornEvent.OutputTuple,
      AdornEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TreeCreated(address,uint256)": TypedContractEvent<
      TreeCreatedEvent.InputTuple,
      TreeCreatedEvent.OutputTuple,
      TreeCreatedEvent.OutputObject
    >;
    TreeCreated: TypedContractEvent<
      TreeCreatedEvent.InputTuple,
      TreeCreatedEvent.OutputTuple,
      TreeCreatedEvent.OutputObject
    >;
  };
}
