/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Multicall__factory } from "./Multicall__factory.js";
export { XmasTree__factory } from "./XmasTree__factory.js";
